### ISSUE TITLE
AttributeError: type object 'spmatrix' has no attribute '__div__'

### ISSUE THREAD

**Issue by Tanpo7** [hudson-and-thames/arbitragelab#102]
* ArbitrageLab: `python -m arbitragelab --version`
* Python version: `python --version`

### Description

After installing arbitagelab if I try to import this library I get an AttributeError: type object 'spmatrix' has no attribute '__div__'. I am running jupyter notebook on VSCode, Windows11... I also tried on Google Colab the same error persists.

**Comment by a1215894054** [comment]
I encounter the same issue

**Comment by Jackal08** [comment]
Are you using python 3.8? Its the only version we support for now - will upgrade it soon. 

Id bet its the python version.

**Comment by a1215894054** [comment]
Thank you very much for the reminder.  Also thank you so much for open source this great library! Your efforts are apppreciated.在 2024年4月16日，11:06，Jacques Joubert ***@***.***> 写道：﻿
Are you using python 3.8? Its the only version we support for now - will upgrade it soon.
Id bet its the python version.

**Comment by Tanpo7** [comment]
> Are you using python 3.8? Its the only version we support for now - will upgrade it soon. 
> 
> Id bet its the python version.

Thanks! Using Python 3.8 worked
